# Generated by Django 5.1.5 on 2025-01-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manage_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('cost_info', models.IntegerField()),
                ('basic_time', models.IntegerField()),
                ('basic_cost', models.IntegerField()),
                ('unit_time', models.IntegerField()),
                ('unit_cost', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('open_day', models.CharField(max_length=50)),
                ('weekday_open', models.CharField(max_length=50)),
                ('weekday_close', models.CharField(max_length=50)),
                ('saturday_open', models.CharField(max_length=50)),
                ('saturday_close', models.CharField(max_length=50)),
                ('holiday_open', models.CharField(max_length=50)),
                ('holiday_close', models.CharField(max_length=50)),
                ('pay_method', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('disabled_person', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avail', models.IntegerField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_info', to='demos.parkinglot')),
            ],
        ),
    ]
