# Generated by Django 5.1.5 on 2025-02-07 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteParking',
            new_name='UserFavoriteParking',
        ),
    ]
