# Generated by Django 5.1.5 on 2025-02-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='available_spots',
            field=models.IntegerField(default=0),
        ),
    ]
