# Generated by Django 5.1.5 on 2025-01-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='parking_type',
            field=models.CharField(default='공영', max_length=50),
            preserve_default=False,
        ),
    ]
