# Generated by Django 5.1.5 on 2025-01-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='disabled_person',
            new_name='disabled_parking',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='basic_cost',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='basic_time',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='cost_info',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='holiday_close',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='holiday_open',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='manage_id',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='open_day',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='parking_type',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='pay_method',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='saturday_close',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='saturday_open',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='unit_time',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='weekday_close',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='weekday_open',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='base_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='base_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='extra_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='extra_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='fee_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='holiday_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='holiday_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='lot_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='road_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='saturday_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='saturday_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='weekday_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='weekday_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
