# Generated by Django 5.1.5 on 2025-02-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일'),
        ),
    ]
