# Generated by Django 5.1.5 on 2025-02-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
