# Generated by Django 5.1.5 on 2025-02-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_alter_parkinglot_available_spots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='available_spots',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
