# Generated by Django 5.1.5 on 2025-01-31 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_rename_disabled_person_parkinglot_disabled_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='demos.parkinglot'),
        ),
    ]
