# Generated by Django 5.1.5 on 2025-02-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_parkinglot_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='average_rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
