# Generated by Django 5.1.5 on 2025-02-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0005_favoriteparking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteParking',
        ),
    ]
