# Generated by Django 5.1.5 on 2025-01-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phonenumber'),
        ('user', '0003_user_created_at_alter_user_last_login'),
    ]

    operations = [
    ]
